# config/packages/stimulus.yaml
stimulus:
    # the default values
    controller_paths:
        - '%kernel.project_dir%/assets/controllers'
        - '%project.ux_components.dir%'
    controllers_json: '%kernel.project_dir%/assets/controllers.json'
