twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    form_themes:
        - 'form/theme.html.twig'
    paths:
        '%project.ux_components.dir%': components # How to let PhpStorm IDE autocomplete work, in this example I set "components" as alias and "components" as folder, https://stackoverflow.com/q/35148786
        '%project.public_dir%': public

when@test:
    twig:
        strict_variables: true
